name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./backend

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        working-directory: ./backend

      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest
        working-directory: ./backend

      # --- NEW STEP ADDED HERE ---
      - name: Run health check
        run: |
          # Install uvicorn and any other server dependencies
          pip install uvicorn httpx
          
          # Start the server in the background
          # We remove --reload as it's not needed for a CI check
          uvicorn app:app --host 0.0.0.0 --port 8000 &
          
          # Wait for the server to start up (5 seconds)
          sleep 5
          
          # Check if the server is responding on the root URL
          # The --fail flag causes curl to exit with an error if the HTTP request fails
          curl --fail http://localhost:8000/
          
          # You could add more endpoints to test here
          # curl --fail http://localhost:8000/api/v1/items
        working-directory: ./backend
