# The name of the workflow
name: Manually Run Backend Tests

# This section is changed to allow manual runs ONLY
on:
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          # Optional: Caches pip dependencies to speed up future runs
          cache: 'pip'
          cache-dependency-path: 'backend/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./backend

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        working-directory: ./backend

      

      - name: Run health check
        run: |
          pip install uvicorn httpx
          python app.py &
          sleep 5
          curl --fail http://localhost:8000/
        working-directory: ./backend
